spring.application.name=xushu-claude

 logging.threshold.console=ERROR

spring.ai.deepseek.api-key=sk-cp-sUaMnvzKlS1-vYctrINI1Jxx8bDrgmJ2784JaLAO1DnupBLHGRAQfJPUCqQnQu2F7M5g8zXXsCj40_KaZxcqeGtA7l_CwPLBKWCNhgx6eGvPeX7ZaGguaYI
spring.ai.deepseek.chat.model=MiniMax-M3
spring.ai.deepseek.chat.base-url=https://api.minimax.cn/v1

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.mcp.client.stdio.servers-configuration= classpath:/mcp/mcp-servers-config.json
