spring.application.name=xushu-claude

 logging.threshold.console=ERROR

spring.ai.deepseek.api-key=${MINIMAX_API_KEY}
spring.ai.deepseek.chat.model=MiniMax-M3
spring.ai.deepseek.chat.base-url=https://api.minimax.cn/v1

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.mcp.client.stdio.servers-configuration= classpath:/mcp/mcp-servers-config.json
